### PR TITLE
construction days left text question

### PR DESCRIPTION
**Pull request by wchristian**
i can't find these two in the strings in a useful manner, are they images? (extracted from #7)

image

### CODE REVIEW

**Comment by miyagami** [comment]
"残り日数"  - Remaining Number of Days", or brief, "Days Remaining"

..\sharedassets5\Textures/ArsenalBuild.tex

**Comment by wchristian** [comment]
I've changed the PR to remove those two lines. Does it make sense for you to keep this one open or should i close it?

**Comment by miyagami** [comment]
What do you mean by "Remove" ?

**Comment by wchristian** [comment]
I had "残り" and "日数"  as unique segments in the dictionary to try and find where they might be, but given they're in a texture they're just noise to me.

**Comment by miyagami** [comment]
Ah. okay.

**Comment by wchristian** [comment]
Since my other question was vague i guess: Would it be helpful for you to have a ticket that collects "looks like text but needs to be done in texture" ticket?

**Comment by miyagami** [comment]
> Since my other question was vague i guess: Would it be helpful for you to have a ticket that collects "looks like text but needs to be done in texture" ticket?

That would be most excellent.

**Comment by limyz** [comment]
I can do up image replacements to indicate them as days. Suggest to assign PR to me then approve for merge

**Comment by miyagami** [comment]
> I can do up image replacements to indicate them as days. Suggest to assign PR to me then approve for merge

No reason to.
I am doing the image replacements.

I have all the remaining untranslated text in the .tex files translated, minus I think three sets of strings I am still working on localizing, and will be doing the actual editing soon.

**Comment by limyz** [comment]
Nice.  Will keep a lookout on issues

**Comment by wchristian** [comment]
This particular topic is handled and done with #32 and #34.

**Pull request closed without merging**
