### PR TITLE
map screen button guide translations

### PR DESCRIPTION
**Pull request by wchristian**
This contains some of the translations previously in #7.

image

### CODE REVIEW

**Comment by miyagami** [comment]
This needs work.

**Comment by miyagami** [comment]
Try this: 

Strategy : Admiral Comm : Info[rmation] : Pick : Sea Area : End of Turn

**Comment by wchristian** [comment]
As of 0.4.305_001 this looks as follows:
image

The Command on Strategy is too long, Fleet Information was truncated, and Selection was wrapped onto the next line in both cases.

I updated the PR to this:

Strategy Cmd : Admiral Comm : Fleet Info : Fleet Select : Region Select

Does that make sense? Is Comm or Cmd better?

Still need to try how that actually renders.

**Comment by miyagami** [comment]
I think Cmd would make more sense as the standard.

Honestly, I really liked how this looked, except for the earlier comment to change FleetI to Info.
However, I understand the need to change Strategy to Strategy Cmd.
50515508-74fb0400-0aa5-11e9-8da1-f1f2dc96f1e5
And i think Region works.
I actually did consider changing Comm to Conn. After the concept of a Conning Tower.

How do you think about just calling the Circle button to just "Enter" or some derivative of that concept? Because, it really is just a select/verify button on that map.

**Comment by wchristian** [comment]
Ok, thanks for the info, i can try and generate a few renderings of variations.

Also note that in the diff the left side is your most recent set of translations (region as well) and the right side is just what seems to make sense. I have no preferences on any of those really.

Calling circle "enter" there might be possible, but would require new code, as 戦略コマンド would still be strategy command in other places.

**Pull request closed without merging**
