### PR TITLE
quest screen

### PR DESCRIPTION
**Pull request by wchristian**
Some quest screen translations extracted from #7.

image

### CODE REVIEW

**Comment by limyz** [comment]
Looks awesome

**Comment by wchristian** [comment]
@limyz Thanks. :)

The questions that we'll now have to consider are:

Are there translations for "Confirm missions details" that are smaller so it doesn't squish the text and still accurate or do we leave it like that?

Is there a wording for the top text that'd fit the number in a gap, or do i need to try and add spaces to push the text to the right? If pushing it makes it so long that it crashes, can it be shortened?

**Comment by miyagami** [comment]
> Are there translations for "Confirm missions details" that are smaller so it doesn't squish the text and still accurate or do we leave it like that?

Confirm Mission works just as well.

> Is there a wording for the top text that'd fit the number in a gap, or do i need to try and add spaces to push the text to the right? If pushing it makes it so long that it crashes, can it be shortened?

Is it self centering?
Try pushing it to the right with:  "new duties remain."

**Comment by wchristian** [comment]
I've changed to Confirm Mission.

- [ ] Gonna try pushing it to the right.

**Comment by wchristian** [comment]
image

**Pull request merged**
