### PR TITLE
options translations

### PR DESCRIPTION
**Pull request by wchristian**
I think the title text is a texture.

image

(Extracted some trs from #7.)

### CODE REVIEW

**Comment by wchristian** [comment]
Not too happy with operation guide. Also i think you mentioned "options" as an alternative for Settings?

**Comment by limyz** [comment]
設定 does translate to Settings. Either way, both are functional texts.

**Comment by wchristian** [comment]
@limyz Functional, yeah, but Settings overflows the space it has a little and it'd be nice to have fluent localization. :)

I'm thinking button guide, but that's a naive first idea.

For settings i'm also tempted to make it "Change", as that describes better what the left-right d-pad does.

Slightly unhappy about the Choose overflowing too.

I've also mentioned to @miyagami that ence we've translated everything to english we might switch fonts again for an ascii-only font with thinner letters.

**Comment by miyagami** [comment]
> Not too happy with operation guide. 

操作ガイド : Literally translates to Operation Guide. 


>Also i think you mentioned "options" as an alternative for Settings?

"Option(s)" is a good standby. Not sure where that is in the files, I would have to go through a lot of .tex files to find if it is or is not there.

**Comment by wchristian** [comment]
I don't feel great about Operation Guide because to my understanding that phrase doesn't easily describe "this thing makes the button list show up", but if you think it's fine i can leave it like that. Is this the case?

Your comment means you don't like "Change" instead of options?

- [x] will change to Options
- [x] have to check textures for title text

**Comment by miyagami** [comment]
To be honest, I have no idea what that option does.
If it makes the bar on the bottom show up, then calling it an Operations Guide does make sense. Because it would be a guide for the various operations the buttons can provide.
If it does something else, then I will need to think about it differently. Or, at least test it.

I prefer Select over Change. Select is the up/down movement. Change would work good for Settings.
設定 Should be Settings or Options.
That should be more specific.

**Comment by wchristian** [comment]
Integrated with 設定 as "Set".

**Pull request merged**
