### PR TITLE
achievement popup translations

### PR DESCRIPTION
**Pull request by wchristian**
These are extracted from #7.

They're the little black texts that pop up bottom right. Hopefully fairly uncontroversial.

However care must be taken as the achievement titles are the same as the tutorial titles from #18.

image
image
image
image

### CODE REVIEW

**Comment by miyagami** [comment]
Not sure calling them achievements would not cause confusion as the game has achievements as common gamer parlay uses. But, for now, i get what you mean.

**Comment by limyz** [comment]
Calling them "in-game achievements" will avoid this confusion.

**Comment by wchristian** [comment]
I don't think they're ever called achievements in game.

Is there maybe a better word for "achieved"?

**Comment by limyz** [comment]
Completed would be an alternative.

**Comment by miyagami** [comment]
Go with "Finished", or if that is too long, "Get".

**Comment by wchristian** [comment]
As these have been superceded by the recent translation push, i'm closing this out.

**Pull request closed without merging**
