### PR TITLE
some tutorial popup translations

### PR DESCRIPTION
**Pull request by wchristian**
Extracted some more translations from #7.

Is the blue fast build button a texture or a string?

image
image
image
image
image
image
image

### CODE REVIEW

**Comment by wchristian** [comment]
The tutorial titles are the same as the achievement popup titles in #21.

**Comment by miyagami** [comment]
> Extracted some more translations from #7.
> 
> Is the blue fast build button a texture or a string?

..\sharedassets5\Textures\ArsenalBtn.tex
arsenalbtn tex

**Comment by wchristian** [comment]
Thanks, so it's not that.

- [x] fix the space before construction
- [ ] dig with unity tools to identify location/purpose of "高速建造"
- [ ] add translations for remaining tutorial texts

**Comment by wchristian** [comment]
Updated this one on top of the current master branch and it now modifies some of the existing translations, would be good to review and adapt/discard as appropriate.

**Pull request closed without merging**
