### PR TITLE
activate some previous translations

### PR DESCRIPTION
**Pull request by wchristian**
In this one i mark the confirmed locations of these strings in the binary files, thus enabling them for the next patch. Mainly asking for sign-off here, and to inform that this will be happening.

Also a note: Coordinated shelling is so much bigger than the source string that it's quite possible to cause a crash. Needs to be tested after integration.

### CODE REVIEW

**Comment by miyagami** [comment]
I have been trying to think of a better way to approach Coordinated Shelling for some days now. Maybe we will have to abbreviate it.

**Comment by wchristian** [comment]
Possible. Can you maybe tell me how to reach it? Then i can check immediately if it crashes.

**Comment by miyagami** [comment]
I am not sure I understand the request.

Reach it in the script? 
Reach it in the .tex files?
Reach it in game?
Reach it ???

**Comment by wchristian** [comment]
Reach the place in the game interface where I can see that string being used. :)

**Comment by miyagami** [comment]
So far, all i have found of it is here, which uses a .tex file


.tex file [purple added for contrast, red lines added to help find]
..\sharedassets11\Textures\CommandUnit Atlas.tex.png



also, 
指揮ボックス選択 is "Command Box Selection"
外す is "Remove" or "Drop"
一括解除 is "Batch Remove/Cancel" or even "Remove/Drop All"

**Pull request closed without merging**
