### PR TITLE
first cut on a code of conduct

### PR DESCRIPTION
**Pull request by wchristian**
For a number of reasons a code of conduct is a useful addition to this project. The proposed document is an adapatation of the geekfeminism code of conduct, with the following variables used:

COMMUNITY NAME = KCV Translation
RESPONSE TEAM = community management
LEADERSHIP TEAM = admins

As well as a few changes:

- commitment that all complaints are evaluated and acted upon
- clarification that the list is not exclusive and violations of the spirit of the document can also result in action
- any behavior which results in being expelled will also result in their name being removed from the credits
- a reference to racism replaced with "ethnic background"

The email address mentioned is created by me on gmail and will be set up to forward to community management team members. @miyagami will also receive administrative login to the account.

Questions, comments?

### CODE REVIEW

**Comment by wchristian** [comment]
Please note that these links will provide a more readable rendering of these files:

https://github.com/wchristian/kc-vita-translation/blob/d93505fde2fe455502312068a42855954c41bff4/README.md

https://github.com/wchristian/kc-vita-translation/blob/d93505fde2fe455502312068a42855954c41bff4/CODE_OF_CONDUCT.md

**Comment by wchristian** [comment]
Also, another matter of documentation: As the gmail forwarding feature isn't the best, i am using filters set to "-asdasdlsdafjkhasdfkljhsadfhklh" to have it catch and forward all emails to individual targets.

**Comment by miyagami** [comment]
We should get that up on the pages easy to find/see. 
I have no problems with it at this time, but I may reserve the right to change parts of it in the future.

**Comment by wchristian** [comment]
As by agreement from chat, merged this into master.

**Pull request merged**
